# Generated by Django 5.0.6 on 2024-10-05 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 5), verbose_name='تاریخ'),
        ),
    ]
