# Generated by Django 5.0.6 on 2024-07-06 15:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('extract', models.TextField(verbose_name='خلاصه')),
                ('slug', models.SlugField(verbose_name='ادرس')),
                ('photo', models.ImageField(upload_to='photo/%y/%m/%d', verbose_name='تصویر')),
                ('date', models.DateField(default=datetime.date(2024, 7, 6), verbose_name='تاریخ')),
                ('Price', models.IntegerField(verbose_name='قیمت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول ها',
            },
        ),
    ]
